### ISSUE TITLE
Release FoundationStereo model and dataset on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [NVlabs/FoundationStereo#17]
Hi @wenbowen123 🤗

Niels here from the open-source team at Hugging Face. I discovered your work on Arxiv and was wondering whether you would like to submit it to [hf.co/papers](https://hf.co/papers) to improve its discoverability.If you are one of the authors, you can submit it at https://huggingface.co/papers/submit.

The paper page lets people discuss about your paper and lets them find artifacts about it (your models, datasets or demo for instance), you can also claim
the paper as yours which will show up on your public profile at HF, add Github and project page URLs.

It'd be great to make the checkpoints and dataset available on the 🤗 hub, to improve their discoverability/visibility.
We can add tags so that people find them when filtering https://huggingface.co/models and https://huggingface.co/datasets.

## Uploading models

See here for a guide: https://huggingface.co/docs/hub/models-uploading. 

In this case, we could leverage the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds `from_pretrained` and `push_to_hub` to any custom `nn.Module`. Alternatively, one can leverages the [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file) one-liner to download a checkpoint from the hub. 

We encourage researchers to push each model checkpoint to a separate model repository, so that things like download stats also work. We can then also link the checkpoints to the paper page.

## Uploading dataset

Would be awesome to make the dataset available on 🤗 , so that people can do:

```python
from datasets import load_dataset

dataset = load_dataset("your-hf-org-or-username/your-dataset")
```
See here for a guide: https://huggingface.co/docs/datasets/loading.

Besides that, there's the [dataset viewer](https://huggingface.co/docs/hub/en/datasets-viewer) which allows people to quickly explore the first few rows of the data in the browser.

Let me know if you're interested/need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by wenbowen123** [comment]
@NielsRogge that sounds great! Just emailed you some questions.

**Comment by NielsRogge** [comment]
I can't seem to find the email, would you be able to add them here?

**Comment by wenbowen123** [comment]
@NielsRogge I was not able to add our paper on HF any more. I got the error: "the paper is more than 7 days and cannot be submitted to daily papers"

**Comment by NielsRogge** [comment]
Thanks, just found it, apologies.

Yes we just merged an update so that this can be extended to 14 days. You can still index your paper as explained here: https://huggingface.co/docs/hub/en/paper-pages#can-i-have-a-paper-page-even-if-i-have-no-modeldatasetspace

**Comment by wenbowen123** [comment]
@NielsRogge I just tried again and it's still showing the 7days error. Btw, our arxiv version was first submitted a few months ago, not sure if the 7/14 days policy is using the latest arxiv upload or the earliest one.

**Comment by NielsRogge** [comment]
I've indexed the paper for you: https://huggingface.co/papers/2501.09898. Feel free to claim it as an author, so that it shows up on your Hugging Face profile.

Yeah it's because there'a new version released on Arxiv I see. 

Let me know if you need any help uploading the weights! Would be cool to have it at https://huggingface.co/nvidia

**Comment by NielsRogge** [comment]
Could we keep this issue open so we can track it? 🙏

**Comment by NielsRogge** [comment]
Hi @wenbowen123 I saw the weights are released on Google Drive. Could you try out the following - assuming you make the FoundationStereo class inherit from [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin)?

```python
from core.foundation_stereo import FoundationStereo

model = FoundationStereo(...)

# equip with weights
model.load_state_dict(...)

# push to the hub
model.push_to_hub("nvidia/foundation-stereo")

# now anyone can use it as follows:
model = FoundationStereo.from_pretrained("nvidia/foundation-stereo")
```

**Comment by wenbowen123** [comment]
@NielsRogge When pushing the model, I'm getting error 
```
403 Forbidden: You don't have the rights to create a model under the namespace "nvidia".
Cannot access content at: https://huggingface.co/api/repos/create.
Make sure your token has the correct permissions.
```

Seems like I need to ask for permission from the account manager on our end?

**Comment by NielsRogge** [comment]
Yes correct, your HF account would need to be added to the NVIDIA org and you would need to get contributor or write permissions.
